### PR TITLE
Add redundant dependency elimination.

### PR DESCRIPTION
**Pull request by Sashank999**
I have added comments to make code clear. Let me know if there are any modifications that I must make.

### CODE REVIEW

**Comment by polikuo** [comment]
IMO, downloading tree is not exactly a good idea.
The new extension may not be published yet.
I've seen tree files from the repo is corrupted because infinite loop.
You can try writing a DFS function which is more dynamic.

**Comment by bdantas** [comment]
Hi Shashank999 and polikuo. I like the idea but I agree with polikuo that the check needs to work both for extensions that already exist in repo (i.e., for extensions that are being updated) as well as for brand-new extensions.

I tried to test this pull request but an executable called _stringinstring_ (e.g., on line 1682) does not exist on my system. provides.sh does not give me any hits in the repo, either. A _stringinstring_ function probably needs to be defined?

**Comment by polikuo** [comment]
Hi, I review some of my old notes and found a helpful awk script that runs faster.
[del_redundant.awk.txt](https://github.com/user-attachments/files/18138574/del_redundant.awk.txt)

Run this example script in **/etc/sysconfig/tcedir/optional** like this:
`cat list.of.dep | /tmp/del_redundant.awk`

We could adjust the function so that it also read the current submitqc working directory.

**Comment by Sashank999** [comment]
> Hi Shashank999 and polikuo. I like the idea but I agree with polikuo that the check needs to work both for extensions that already exist in repo (i.e., for extensions that are being updated) as well as for brand-new extensions.
> 
> I tried to test this pull request but an executable called _stringinstring_ (e.g., on line 1682) does not exist on my system. provides.sh does not give me any hits in the repo, either. A _stringinstring_ function probably needs to be defined?

Hello bdantas.
_stringinstring_ is provided in `/etc/init.d/tc-functions`. It is an ash function. I ran the tests with `-c` color option so the file got included which provided the function for me. I should probably remove the function or add an implementation in submitqc.



> IMO, downloading tree is not exactly a good idea. The new extension may not be published yet. I've seen tree files from the repo got corrupted because infinite loop. You can try writing a DFS function which is more dynamic.
> 
> For example, [this](https://github.com/polikuo/practice/blob/master/get-dep-list#L142) is a DFS function. Or, you can use [this ugly for loop](https://github.com/polikuo/practice/blob/master/get-dep-list#L117) to remove redundent tczs.

> Hi, I review some of my old notes and found a helpful awk script that runs faster. [del_redundant.awk.txt](https://github.com/user-attachments/files/18138574/del_redundant.awk.txt)
> 
> Run this example script in **/etc/sysconfig/tcedir/optional** like this: `cat list.of.dep | /tmp/del_redundant.awk`
> 
> We could adjust the function so that it also read the current submitqc working directory.

Hello polikuo.
Thank you for the references. I also initially thought of using .dep files for scanning, as per [Rich's suggestion](https://forum.tinycorelinux.net/index.php/topic,27407.msg176471.html#msg176471) in the forums for my previous script. But .tree files seemed easier for an initial PR and feedback from others.
Thank you for your DFS function. I still don't know much about awk scripts so I should start learning, but I doubt its performance would be significantly better than ash script.
I forgot to consider the .dep files in the user's TCE directory. IMO, they may not always be up-to-date to the repo, which is why I was mentioning about fetching the files from the repo.
What do you think of fetching ? Should we use local TCE directory or fetch all .dep files from the repo ?
The local .dep files from the submitqc's invocation directory will be included anyway. Its about the other .dep files.

On a separate note, why would the .tree files get corrupted ? Are they even used by tce scripts such as `tce-load` and `tce-size` ?

**Comment by polikuo** [comment]
> On a separate note, why would the .tree files get corrupted ? Are they even used by tce scripts such as `tce-load` and `tce-size` ?
It happens, quite frequent actually, some typo here and there resulting truncated tree or infinite loop when two tczs "depending" on each other when they shouldn't.

> Thank you for your DFS function. I still don't know much about awk scripts so I should start learning, but I doubt its performance would be significantly better than ash script.
**ToPrint** is a hash table
**line** is the key, which is the name of tcz
set value to 1 for printing; change it to 0 when it's spotted in others' dep

**Comment by bdantas** [comment]
> Hello bdantas. _stringinstring_ is provided in `/etc/init.d/tc-functions`. It is an ash function. I ran the tests with `-c` color option so the file got included which provided the function for me. I should probably remove the function or add an implementation in submitqc.
 
Hi Sashank999. Sorry for missing that _stringinstring_ is in tc-functions. No need to reimplement it, you can just add _. /etc/init.d/tc-functions_ somewhere in the submitqc script to use the existing implementation.

I tested your pull request with .dep files which I edited to intentionally contain redundant dependencies. Things seem to work as advertised when I'm just updating an extension that already exists in repo:

```submitqc: brave-browser.tcz contains redundant dependencies (extension families) in .dep file ? 
Originally found 7 deps
Now reduced to 6.
Ok.
```

As polikuo warned, things do not work as intended when it's a brand-new extension (submitqc claims there is no .dep file in the directory being qc'd, which just-testing.tcz.dep clearly exists):
```
submitqc: just-testing.tcz contains redundant dependencies (extension families) in .dep file ? No .dep file. Ok.
```
This should be fixed somehow, perhaps using one of polikuo's suggestions.

**Comment by Sashank999** [comment]
> As polikuo warned, things do not work as intended when it's a brand-new extension (submitqc claims there is no .dep file in the directory being qc'd, which is an error because just-testing.tcz.dep does exist):
> 
> ```
> submitqc: just-testing.tcz contains redundant dependencies (extension families) in .dep file ? No .dep file. Ok.
> ```
> 
> This should be fixed somehow, perhaps using one of polikuo's suggestions.
Hello bdantas.
I just tested it, it works. I ran it by creating a 8zip.tcz (renamed from 15.x/x86_64/7zip.tcz) and creating a 8zip.tcz.dep from a few entries of 15.x/x86_64/wifi.tcz.tree .
I have the file successfully reduced from 12 dependencies to 1 dependency.

For reproducing, I attached the files.
[8zip.tar.gz](https://github.com/user-attachments/files/18139116/8zip.tar.gz)

**Comment by Sashank999** [comment]
> **ToPrint** is a hash table **line** is the key, which is the name of tcz set value to 1 for printing; change it to 0 when it's spotted in others' dep
> 
> You won't find that on regular ash, you'll need bash
Hello polikuo.
Its not that I don't understand its working. I need to be able to modify the script so that it can work with repo files and other inputs as well. For that, I need some time off to learn awk.
If possible, I would like to stick to busybox awk and busybox ash.

**Comment by bdantas** [comment]
Hi Sashank999. I must have fat-fingered something before. It does work with brand-new extensions. Strong work!

I think it just need 3 small tweaks:
1. add an entry to the Changes section with brief description of your change
2. Update the VERSIONSTRING
3. Add `. /etc/init.d/tc-functions` to the SETUP section
 
Hi polikuo. Anything you'd add at this point? Someone perhaps could make the redundant dependency check faster, but this is working as-is and I think adds great value to the script.

**Review by bdantas — CHANGES_REQUESTED** [review]
Works great. I think it neeeds only new versionstring, entry in Changes section. and sourcing tc-functions. I was going to suggest keeping a backup of the original .dep file, but I see this was already implemented. Nice work.

**Comment by Sashank999** [comment]
> Hi Sashank999. I must have fat-fingered something before. It does work with brand-new extensions. Strong work!
> 
> I think we need just just 3 more small things:
> 
>     1. Add an entry to the Changes section with brief description of your change
> 
>     2. Update the VERSIONSTRING
> 
>     3. Add `. /etc/init.d/tc-functions` to the SETUP section so that `stringinstring` can be used
> 
> 
> In addition, once we merge your redundant dep check, someone should send an updated extension to Juanito. I can take care of this if you like, just let me know.
> 
> Hi polikuo. Anything you'd add at this point? Someone perhaps could make the redundant dependency check faster, but this is working as-is and I think adds great value to the script.

Hi bdantas.
I can happily add the changelog entry and package it. But I am still trying awk scripts as mentioned by polikuo. I am trying to find something with awk so that it will be faster.
Moreover, after this conversation, I think we need to use .dep files instead of .tree files. If you or Juanito can check if there are really such broken tree files, I can rewrite the algoritm to use .dep files.

**Comment by bdantas** [comment]
> Edit: Is there any dep.db.gz like there is provides.db.gz in the repository ? This would really simplify and change everything.
 
Yes, there is dep.db.gz. I think since TCL14. I agree that it makes many things easier. (I use it in `/usr/bin/update-everything`, for example.)

**Review by bdantas — APPROVED** [review]

**Comment by polikuo** [comment]
Looking good, just tested with new extensions for armhf.
Merging...

**Pull request merged**
