### PR TITLE
updates

### PR DESCRIPTION
**Pull request by polikuo**
import from repo
indention, trailing blank space adjustment
bug fix
function rewrite
tested

### CODE REVIEW

**Comment by bdantas** [comment]
Hi polikuo. Thank you for refactoring. I tested your pull request against a test extension with intentional ownership issues:

```
$ unsquashfs -lls 88x2bu.tcz
drwxr-xr-x bruno/staff              26 2023-08-29 09:27 squashfs-root
drwxr-xr-x bruno/staff              28 2023-08-29 09:24 squashfs-root/usr
drwxr-xr-x bruno/staff              47 2023-08-29 09:27 squashfs-root/usr/local
drwxr-xr-x bruno/staff              30 2023-08-29 09:19 squashfs-root/usr/local/lib
drwxr-xr-x bruno/staff              39 2023-08-29 09:19 squashfs-root/usr/local/lib/modules
drwxr-xr-x bruno/staff              29 2023-08-29 09:20 squashfs-root/usr/local/lib/modules/6.1.2-tinycore64
drwxr-xr-x bruno/staff              30 2023-08-29 09:20 squashfs-root/usr/local/lib/modules/6.1.2-tinycore64/kernel
drwxr-xr-x bruno/staff              26 2023-08-29 09:20 squashfs-root/usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers
drwxr-xr-x bruno/staff              31 2023-08-29 09:20 squashfs-root/usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers/net
drwxr-xr-x bruno/staff              32 2023-08-29 09:20 squashfs-root/usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers/net/wireless
-rw-r--r-- bruno/staff         5453112 2023-08-28 22:40 squashfs-root/usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers/net/wireless/88x2bu.ko
drwxrwxr-x root/staff               29 2023-08-29 09:25 squashfs-root/usr/local/tce.installed
-rwxr-xr-x root/staff               69 2023-08-29 09:25 squashfs-root/usr/local/tce.installed/88x2bu
```
Your version of submitqc seems to have 3 issues: 

* it errors out at line 668 because checkcopyright() is an empty function. If you don't want this check it should be factored out of script or at least needs a return statement
* after I fix the above by adding a return statement, submitqc warns me (correctly) that my .tcz has fileperms issues and advises me to use the --fix flag to fix them
* when I use the --fix flag, it errors out because it is looking for files in the filesystem rather than in the extension:
```
$ submitqc --fix
...
submitqc: 88x2bu.tcz file/directory ownerships & permissions ok? 

	Expected root:root ownership:
		.
		usr
		usr/local
		usr/local/lib
		usr/local/lib/modules
		usr/local/lib/modules/6.1.2-tinycore64
		usr/local/lib/modules/6.1.2-tinycore64/kernel
		usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers
		usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers/net
		usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers/net/wireless./usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers/net/wireless/88x2bu.ko

	fixing inconsistencies ... 
	chown root:root files and directories
chown: cannot access './usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers/net/wireless./usr/local/lib/modules/6.1.2-tinycore64/kernel/drivers/net/wireless/88x2bu.ko': No such file or directory

Error in chown - halting.
```

**Comment by bdantas** [comment]
Hi, polikuo. You can call me either. I'm Bruno to real-world friends, so prefer that :)

checkcopyright() was correct in your pull request. I must have fat-fingered something. It's correct again in commit e19e49d. Sorry for the noise.

When I made some tweaks to submitqc a few months ago (March 2023), I opted to make the ownership/permissions fixes automatic. Rich also thought it was a good idea. But it's your call now. It's a fix I need every time but I could get used to the _--fix_ flag.

My only request is that, when ownerships/permissions are fixed (whether automatically or with the flag), _all_ ownerships and permissions are correct. This should include _tc:staff_ ownership of the root of the extension (the squashfs-root directory)**.

** Otherwise, extension _someapp_ built by me (or by anyone who uses _user=somename_ bootcode), when loaded on someone else's TCL machine with vanilla settings (i.e., no _copy2fs_ flag and no _user=someone_ bootcode), will have _1000:staff_ ownership of _/tmp/tcloop/someapp_, which is ugly as heck.

**Comment by polikuo** [comment]
Hi, Bruno.
Adjustments done.
Have a look at it, I'll send the package if all looks well.

**Comment by bdantas** [comment]
Hi polikuo. I removed _--fix_ from usage info and adjusted indentation for _--no-fix_ info.

Just one last observation: 

The [wiki](https://wiki.tinycorelinux.net/doku.php?id=wiki:creating_extensions#adding_custom_startup_scripts) recommends 755 for general executables but 775 for the startup script (note the recursive `sudo chmod -R 775` on tce.installed). It's just cosmetic but I think it would be nice for the script to follow wiki recommendations all the way. Agree?

**Comment by polikuo** [comment]
Hi, Bruno.

> note the recursive sudo chmod -R 775 on tce.installed

I know that part, if we're following the wiki, then sure, we could do that.
It's cosmetic and I was too lazy to adjust that.
The fact is, tce-load doesn't care, the script is always run by sudo privilege.
Anyway, to keep everything consistent with the wiki document, here's another quick commit.

**Comment by bdantas** [comment]
Hi polikuo. I use submitqc a lot. Thanks for making it better. 
 
Kindly include the trivial fix on line 789 (see commit 47f96fc) when you submit the extension.
 
Happy hacking!

**Comment by polikuo** [comment]
Hi, Bruno.

> Kindly include the trivial fix on line 789

Nice catch, the older code was _printf_, which would handle the tab and the newline right.
I switch it to _echo_ later cause I sometimes see some hiccup here and there.
Anyway, I'm mailing it.

Cheers

**Pull request merged**
